### PR TITLE
feat: use 500 as default status code since it's an unhandled error

### PR DESCRIPTION
**Pull request by teofilomonteiro**
## Summary

If an unhandled error boils up, the statusCode by default is -1.  

## Motivation

Explain the **motivation** for making this change. What existing problem does the pull request solve?

## Test plan

Demonstrate the code is solid. Example: The exact commands you ran and their output.

## Closing issues

Fixes #

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

-   [ ] I have read the **CONTRIBUTING** document.
-   [ ] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [ ] I have updated the documentation accordingly.
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by sebastienlevert** [comment]
Thanks for the contribution @teofilomonteiro. In this case, the error you are getting back is probably a client error rather than a server side error. Assigning it to 500 by default wouldn't true in this case as there was an error in sending the request, not in receiving the response. 

Can you expand on the scenario and how it happens in your app? Thanks!

**Comment by teofilomonteiro** [comment]
@sebastienlevert An example I can give you is when your credentials are incorrect. When you make a request the error thrown comes with a status code -1. This is not the correct behaviour. 

Also if you are using a framework like nestjs if you throw an error with status code -1, you break the app. Also sending a -1 is strange. Maybe 500 is better since it was an internal error.

**Comment by sebastienlevert** [comment]
So you are saying that sending an invalid token / without a token results in a -1 in the Graph Response?

**Comment by sebastienlevert** [comment]
If you share a small repro, we'd love to investigate using this. Based on the logic in the Error handler, I don't think we would be missing a status coming from the server for instance.

**Comment by teofilomonteiro** [comment]
Thanks @sebastienlevert! It's a super easy setup.

```typescript
import { ClientSecretCredential } from '@azure/identity';
import { Client } from '@microsoft/microsoft-graph-client';
import { TokenCredentialAuthenticationProvider } from '@microsoft/microsoft-graph-client/authProviders/azureTokenCredentials';

async function main() {
  const tenantId = 'valid_tenant_id';
  const clientId = 'valid_client_id';

  const credential = new ClientSecretCredential(tenantId, clientId, 'wrong_client_secret');
  const authProvider = new TokenCredentialAuthenticationProvider(credential, {
    scopes: ['.default'],
  });

  const client = Client.initWithMiddleware({
    debugLogging: false,
    authProvider,
  });

  await client.api('/domains').get();
}

main();
```

This should replicate the issue 👍  In the end

**Pull request closed without merging**
