### PR TITLE
Remove unsupported node versions(12 & 14) from the pipeline

### PR DESCRIPTION
**Pull request by koros**
A similar PR may already be submitted! Please search among the [Pull request](https://github.com/microsoftgraph/msgraph-sdk-javascript/pulls) before creating one.

Thanks for submitting a pull request! Please provide enough information so that others can review your pull request.

**NOTE: PR's will be accepted only in case of appropriate information is provided below**

## Summary

Remove versions of node that are no longer supported, 12 & 14, from the pipeline build configuration 

## Motivation

Explain the **motivation** for making this change. What existing problem does the pull request solve?

## Test plan

Demonstrate the code is solid. Example: The exact commands you ran and their output.

## Closing issues

Fixes #

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

-   [ ] I have read the **CONTRIBUTING** document.
-   [ ] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [ ] I have updated the documentation accordingly.
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.

### CODE REVIEW

**Review by baywet — CHANGES_REQUESTED** [review]
This needs to be updated too https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/.github/workflows/ci_validation.yml

**Review by baywet — APPROVED** [review]
Thanks for making the changes

**Comment by MIchaelMainer** [comment]
Replaces #1403

**Review by baywet — DISMISSED** [review]

**Comment by MIchaelMainer** [comment]
In cases where we remove a workflow that is required by policy, we need to do one of the following actions:
* Create a PR that removes the deprecated workflow from the policy specification before we remove the workflow. In this PR, we required that the matrix build for node versions 12 and 14 pass before are allowed to merge this PR into the dev branch.
* Elevate to admin to force the merge.

**Review by baywet — APPROVED** [review]

**Pull request merged**
