### PR TITLE
chore: remove unsupported version of node (12) from matrix

### PR DESCRIPTION
**Pull request by MIchaelMainer**

### CODE REVIEW

**Review by baywet — CHANGES_REQUESTED** [review]
We should at least add 18, maybe even 20. And maybe remove 14

**Comment by MIchaelMainer** [comment]
> We should at least add 18, maybe even 20. And maybe remove 14

14 still has a bit more life in it.

**Review by baywet — CHANGES_REQUESTED** [review]
we should probably align the github workflow with that.
And maybe update the policy?
Also have you tried running that workflow? a couple of weeks ago when I tried node 20 for kiota typescript I was getting failures it was impossible to install

**Comment by sebastienlevert** [comment]
What is the impact on calling developers to up our target? Can we impact existing customers? Is that a breaking change?

If we look at https://nodejs.dev/en/about/releases/, 18 and 20 should be the one supported.

**Comment by baywet** [comment]
IMHO yes

**Review by sebastienlevert — CHANGES_REQUESTED** [review]
Can we make this 16-20?

**Comment by sebastienlevert** [comment]
Though, this could mean making it a breaking change for our users. Should we delay with v4 when the work on Kiota is done?

**Comment by koros** [comment]
There were some failing tests after the upgrade so I have addressed those ones on a new PR: https://github.com/microsoftgraph/msgraph-sdk-javascript/pull/1405

**Pull request closed without merging**
