### PR TITLE
Release Preview 2.1.0-2

### PR DESCRIPTION
**Pull request by nikithauc**
The release contains the issues in [Milestone](https://github.com/microsoftgraph/msgraph-sdk-javascript/milestone/1?closed=1)

### CODE REVIEW

**Comment by zengin** [comment]
I don't see the middleware fix in this PR. Is it because it was merged into dev directly?

**Comment by nikithauc** [comment]
> I don't see the middleware fix in this PR. Is it because it was merged into dev directly?

Yes.  The preview release is of dev.

**Comment by zengin** [comment]
I think what was confusing to me was some of the fixes were already in `dev` (middleware) and some others are getting checked in with this PR (null/undefined changes).

**Comment by nikithauc** [comment]
> I think what was confusing to me was some of the fixes were already in `dev` (middleware) and some others are getting checked in with this PR (null/undefined changes).

The null/undefined changes was an issue fixed in [PR](https://github.com/microsoftgraph/msgraph-sdk-javascript/pull/309/) .Replacing the code with a shorthand from a [comment received ](https://github.com/microsoftgraph/msgraph-sdk-javascript/pull/331#discussion_r497559275).

**Comment by zengin** [comment]
Thanks for the explanation and the links.

**Review by zengin — APPROVED** [review]

**Pull request merged**
