### PR TITLE
Make MSALAuthenticationProvider.userAgentApplication public

### PR DESCRIPTION
**Pull request by rjcorrig**
## Summary

Changes access of the `userAgentApplication` member of the `MSALAuthenticationProvider` class to public

## Motivation

Allows the ability to inspect and change the login state, by allowing access to the getUser() and logout() methods on the userAgentApplication member.

## Test plan

Run this code snippet in a sample project to check if the client is logged in, and if so, log it out.

```
const authProvider = new MSALAuthenticationProvider(clientID, graphScopes, options);

const clientOptions: ClientOptions = {
  authProvider: authProvider
};

const client = Client.initWithMiddleware(this.clientOptions);

if (!!authProvider.userAgentApplication.getUser()) { // user logged in?
      authProvider.userAgentApplication.logout();  // log out
}
```

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

-   [x] I have read the **CONTRIBUTING** document.
-   [x] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [ ] I have updated the documentation accordingly.
-   [ ] I have added tests to cover my changes.
-   [x] All new and existing tests passed.

### CODE REVIEW

**Comment by muthurathinam** [comment]
@rjcorrig  Please sign the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoftgraph/msgraph-sdk-javascript?pullRequest=150) 
Refer: https://github.com/microsoftgraph/msgraph-sdk-javascript/pull/150#issuecomment-471190008

**Comment by rjcorrig** [comment]
Waiting for permission from my employer... stay tuned.

**Comment by darrelmiller** [comment]
@rjcorrig We are addressing this issue in a slightly different way in order to be consistent with how it is handled in our other language SDKs.  The AuthenticationProvider will now accept a UserAgentApplication as a constructor parameter.  This means that you can create your own application instance, hold onto it and use it to do Login/Logout etc.

**Comment by rjcorrig** [comment]
@darrelmiller Is that on PR #154 ?

**Comment by darrelmiller** [comment]
@rjcorrig Yes, sorry.  I had intended on including a link to the PR.

**Comment by rjcorrig** [comment]
Cool! That will work for my purposes. I'll go ahead and close this PR. Thanks!

**Pull request closed without merging**
